
module.exports.userService = require('./user.service')
module.exports.staffService = require('./staff.service')
module.exports.tokenService = require('./token.service')
module.exports.authService = require('./auth.service')
module.exports.emailService = require('./email.service')
module.exports.otpService = require('./otp.service')
module.exports.PgService = require('./pg.service')
module.exports.facilitiesService = require('./facilities.service')
module.exports.postService = require('./post.service')
module.exports.userPreferenceService = require('./userPreference.service')
