module.exports.authValidation = require('./auth.validation')
module.exports.userValidation = require('./user.validation')
module.exports.pgValidation = require('./pg.validation')
module.exports.facilitiesValidation = require('./facilities.validation')
module.exports.postValidation = require('./post.validation')
module.exports.staffValidation = require('./staff.validation')
module.exports.userPreferenceValidation = require('./userPreference.validation')